// Writes src/qr.js: the QR matrix for the repository URL (used by segment 12).
import QRCode from 'qrcode';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { REPO } from '../src/config.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const qr = QRCode.create(`https://${REPO.url}`, { errorCorrectionLevel: 'M' });
const n = qr.modules.size;
const rows = [];
for (let y = 0; y < n; y++) {
  let row = '';
  for (let x = 0; x < n; x++) row += qr.modules.get(x, y) ? '1' : '0';
  rows.push(row);
}
const out = `// Generated by tools/make-qr.mjs from REPO.url; do not edit.\nexport const QR = ${JSON.stringify(rows, null, 0).replace(/","/g, '",\n  "').replace('["', '[\n  "').replace('"]', '",\n]')};\n`;
fs.writeFileSync(path.join(root, 'src', 'qr.js'), out);
console.log(`QR ${n}x${n} -> src/qr.js`);
